const listSport = [
  "Tous les sports",
  "Alpinisme",
  "Apnée",
  "Biathlon",
  "Bushcraft",
  "Canyoning",
  "Escalade",
  "Golf",
  "Gravel",
  "Kayak et Canoë",
  "Kitesurf",
  "Mer",
  "Montagne",
  "Multi-activités été",
  "Multi-activités hiver",
  "Neige",
  "Padel",
  "Plongée",
  "Randonnée",
  "Randonnée équestre",
  "Raquettes à neige",
  "Ski alpin",
  "Ski de fond",
  "Ski de randonnée",
  "Ski de randonnée nordique",
  "Ski freeride",
  "Snorkeling",
  "Spéléologie",
  "Surf",
  "Tennis",
  "Trail running",
  "Trekking",
  "Vélo de route",
  "Vélo VTC (loisir)",
  "Voile",
  "VTT et VTT électrique",
  "Windsurf",
  "Wingfoil et Foil",
  "Yoga",
];

export default listSport;
